### ISSUE TITLE
blas used on os x

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/gsl-ocaml#14]
i have installed gsl via homebrew on os x. when i do ` gsl-config --libs` i get `-L/usr/local/Cellar/gsl/2.2.1/lib -lgsl -lgslcblas` which seems to indicate that a brew-provided blas was linked. this is not what the README says, where it is claimed that an optimized blas is linked automatically on os x. i checked also via the Activity Monitor for open files of an ocaml toplevel where gsl was `#require`d. here also, a libgslcblas from homebrew was shown. i could provide the list of open files if desired.

what do i need to do to link to apple's blas? should this be changed to happen automatically even for brew installed gsl?

**Comment by mmottl** [comment]
If I remember correctly, the GSL-provided BLAS/LAPACK libraries will be overridden by the OCaml GSL-bindings.  `gsl-ocaml` links with the Accelerate framework by default.  You can call `otool -L` on your executables to see whether they link with the Accelerate framework.

**Comment by nilsbecker** [comment]
ok, i get:
```
hmtree.native:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/local/opt/gsl/lib/libgsl.19.dylib (compatibility version 22.0.0, current version 22.0.0)
	/usr/local/opt/gsl/lib/libgslcblas.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
which i find confusing since it links with accelerate but also shows the gsl-provided cblas if i'm not mistaken. in that program, also lacaml was used if that matters.

**Comment by nilsbecker** [comment]
ok thanks, will try tomorrow.

**Comment by nilsbecker** [comment]
ok, i tried: i now have this in my local opam-pinned copy of gsl-ocaml:
```
          (*let ic = Unix.open_process_in "gsl-config --cflags --libs" in*)
          let ic = Unix.open_process_in "gsl-config --cflags --libs-without-cblas" in
```
i reinstalled the pinned version with opam. now the same program as before, with otool -L gives 
```
hmtree.native:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/local/opt/gsl/lib/libgsl.19.dylib (compatibility version 22.0.0, current version 22.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
so the cblas is gone. i have not tried if it works yet - in a toplevel with gsl loaded, calls to Gsl_blas seemed to work, although in the open files for that process, nothing with accelerate occured (neither with the gsl-provided cblas)

so i think your suggestion works. i would think this should then be fixed in the opam package?

**Comment by mmottl** [comment]
The more important question is, does the change actually improve performance.  If the Accelerate BLAS overrides the GSL-provided one anyway, the change won't be necessary.  Maybe you can try out matrix multiplication as a test, which should likely show a significant performance difference.

**Comment by nilsbecker** [comment]
hmm it may be that cblas is linked but not used. i tried again with a minimal program which just uses gsl as its only package, and with the original opam-installed gsl. indeed cblas is linked, but so is accelerate, which is here not a byproduct of using lacaml. 
probably performance testing would be the only way to decide.

**Comment by nilsbecker** [comment]
ok. it does seem to matter. i made a program that LU-inverts a 400x400 matrix 100 times. with the standard opam installation of gsl-ocaml this takes 5.9s to run. after pinning gsl-ocaml with the myocamlbuild change above, the same (recompiled) program does not link cblas anymore and runs in 3.0s 

(in each case i reran a few times to be sure)

**Comment by nilsbecker** [comment]
for reference:
```
let a = Gsl.Matrix.create 400 400 in
let () = Gsl.Matrix.set_id a in
let () = Gsl.Matrix.set a 123 223 123. in
for i = 1 to 100 do
  ignore @@ Gsl.Linalg.invert_LU (`M a);
done;
```

**Comment by mmottl** [comment]
Ok, thanks for testing this.  I've made a new release that will avoid linking with the "slow" library on Mac OS X, the reasonable assumption being that users will always want to use the Accelerate Framework on this platform.
