### ISSUE TITLE
symbol import error with 1.21

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/gsl-ocaml#27]
just a heads-up: it seems that 1.21 does not work with gsl 1.15 or lower anymore. not a problem per se. 1.20.2 works with gsl 1.13.

**Comment by mmottl** [comment]
Please feel free to submit patches for any OPAM-related checks or constraints that could avoid build problems of that sort.  Obviously, old versions cannot be supported perpetually.

**Comment by nilsbecker** [comment]
hm, i would but i don't know how version constraints would work for `conf-...` dependencies?

**Comment by nilsbecker** [comment]
actually, on os x, having `brew install gr` would also be a viable option i think. (just for the non-python part)

**Comment by nilsbecker** [comment]
whoops. wrong repository...
