### ISSUE TITLE
gsl header in non-standard location

### ISSUE THREAD

**Issue by hstern2** [mmottl/gsl-ocaml#29]
I'm getting following error, trying to use installation of gsl in non-standard location so no header in /usr/include ...  C_INCLUDE_PATH, CPLUS_INCLUDE_PATH is set to this location, any other env vars to set?  thanks

#=== ERROR while installing gsl.1.21.0 ========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p gsl -j 4
# path         /software/opam/b1/system/build/gsl.1.21.0
# compiler     system (4.06.0)
# exit-code    1
# env-file     /software/opam/b1/system/build/gsl.1.21.0/gsl-73449-ffb3fd.env
# stdout-file  /software/opam/b1/system/build/gsl.1.21.0/gsl-73449-ffb3fd.out
# stderr-file  /software/opam/b1/system/build/gsl.1.21.0/gsl-73449-ffb3fd.err
### stderr ###
# [...]
# Fatal error: exception (Sys_error "/usr/include/gsl/gsl_cdf.h: No such file or directory")
# Raised by primitive operation at file "pervasives.ml", line 389, characters 28-54
# Called from file "src/in_channel.ml", line 20, characters 45-66
# Called from file "src/config/do_cdf.ml", line 96, characters 2-964
#     do_const src/const.{ml,mli} (exit 2)
# (cd _build/default/src && ./config/do_const.exe)
# Fatal error: exception (Sys_error "/usr/include/gsl/gsl_const_cgs.h: No such file or directory")
# Raised at file "src/import0.ml" (inlined), line 237, characters 22-32
# Called from file "src/exn.ml", line 70, characters 6-15
# Called from file "src/config/do_const.ml", line 15, characters 2-1023

**Comment by mmottl** [comment]
The configurator runs `pkg-config` to extract the path to the `gsl` include directory.  You may have to install and/or configure `pkg-config` for that purpose.  Note that `gsl-ocaml` needs access to GSL header files for automatic code generation.

**Comment by mmottl** [comment]
Can you compile `gsl-ocaml` manually?  A simple `make` in the directory should work in principle.  You can take a look at file `src/config/discover.ml` and check whether `let gsl_include =` in that file evaluates to the correct path.

**Comment by mmottl** [comment]
Probably not relevant anymore.
