### ISSUE TITLE
coverage info?

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/gsl-ocaml#7]
It would be good to advertise what of gsl is not covered in some way. I found out after a while that 2d histograms are apparently not included.

**Comment by mmottl** [comment]
The GSL API will surely keep growing over time.  This means that someone would have to continuously monitor what is being added there and update documentation on what's not covered by the OCaml bindings.  A lot of GSL-features are quite arcane to the vast majority of users so there would be a lot of work just documenting missing features that nobody is using anyway. 

Unless a volunteer is willing to do that, I think it's best to just let people run into missing features (rare enough) and either provide a patch (preferred) or add a feature request here on GitHub.

**Comment by nilsbecker** [comment]
fair enough; maybe a rough statement of what percentage is covered, somewhere in the readme? 75%? 95%?

**Comment by mmottl** [comment]
I'm not sure such a percentage would help anybody.  If you need a feature that isn't there, the coverage is 0%, otherwise it's 100% :wink:

**Comment by nilsbecker** [comment]
let's say i want to decide if i want to start a new project in ocaml or another language. i expect to use gsl heavily, and i know what it provides in general, but i don't know yet what exact functions i will need. do i need to prepare for the case that the bindings do not cover a particular function i will need? i think it would be helpful to know at least that the bindings are not complete, and better, roughly how incomplete.

**Comment by mmottl** [comment]
Pretty much all bindings for anything are incomplete, and "sufficient" completeness always depends on your needs.  Lets say I told you that 99% of GSL were covered (whatever that means).  If you need functionality from the missing 1%, the percentage wouldn't help you.  If I told you that only 30% were implemented, but it covers what you need, who cares?

I guess what you actually want to know is the probability that your chosen tools will be good enough for the job.  This depends a lot more on what problem you want to solve than anything else.

**Comment by michipili** [comment]
@nilsbecker For me that information is nicely enough conveyed by the [omcaldoc generated documentation](http://mmottl.github.io/gsl-ocaml/api).
